### ISSUE TITLE
GitHub Actions workflow

### ISSUE THREAD

**Issue by imjasonh** [imjasonh/gke-auth#1]
```yaml
- name: imjasonh/gke-auth@v0.1
  with:
    project: my-project
    location: my-location
    cluster: my-cluster
- run: kubectl get pods
```
